name: "buildkite agent"
description: "run buildkite jobs from github actions"
inputs:
  idleTimeout:
    description: "The maximum idle time in seconds to wait for a job before disconnecting."
    default: "20"
    required: false
  token:
    description: "Your account agent token."
    required: true
runs:
  using: "composite"
  steps:
    - name: cache
      id: cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-buildkite
        path: |
          ~/.buildkite-agent
    - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      name: install
      run: bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh`"
    - name: run
      shell: bash
      run: ~/.buildkite-agent/bin/buildkite-agent start
      env:
        BUILDKITE_AGENT_DISCONNECT_AFTER_IDLE_TIMEOUT: ${{ inputs.idleTimeout }}
        BUILDKITE_AGENT_TAGS: queue=default,queue=${{ github.run_id }}
