name: buildkite-agent

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  buildkite:
    runs-on: ubuntu-latest
    steps:
      - uses: benmoss/buildkite-gh-actions@main
        with:
          token: ${{ secrets.buildkite_token }}
